"""empty message

Revision ID: 615b5cf65da9
Revises: c6d6fee5a63c
Create Date: 2016-04-06 22:38:26.399126

"""

# revision identifiers, used by Alembic.
revision = '615b5cf65da9'
down_revision = 'c6d6fee5a63c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate')
    ### end Alembic commands ###
