"""empty message

Revision ID: c6d6fee5a63c
Revises: 2abdb56dbcd2
Create Date: 2016-04-03 23:30:32.353553

"""

# revision identifiers, used by Alembic.
revision = 'c6d6fee5a63c'
down_revision = '2abdb56dbcd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
